apiVersion: v1
kind: Service
metadata:
  labels:
    run: metabase
  name: lb-metabase
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - targetPort: 3000
    port: 3000
    protocol: TCP
  selector:
    run: metabase
  sessionAffinity: None