apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: metabase
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: kind
    name: metabase
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
status:
  observedGeneration: 1
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: memory
      current:
        averageUtilization: 0
        averageValue: 0