apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: metabase
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metabase
  template:
    metadata:
      labels:
        name: metabase
    spec:
      containers:
      - image: metabase/airton
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: metabase-config
        securityContext:
          runAsUser: 0
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        name: metabase
        resources: {}
